### ISSUE TITLE
Spyder 3.3.6 Not Running on Windows 8.1 

### ISSUE THREAD

**Issue by sagar055** [sagar055/hello-world#1]
Spyder Version 3.3.6 
The tried to launch the spyder application and received the following error:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 186, in main
from spyder.app import mainwindow
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 90, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "C:\ProgramData\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name

**Comment by sagar055** [comment]
The above issue gets resolved, by downgrading the PyQt5 version to 5.10.1.
Ran the below command.
pip install PyQt5==5.10.1
